networks:
  prod:

services:
  backend:
      image: test_backend
      ports:
      - '8000:8000'
      build: 
        context: ./backend
      networks:
        - prod

  frontend:
    build:
      context: ./frontend
    image: test_frontend
    ports:
      - "3000:3000"
    volumes:
      - ./template:/etc/nginx/templates/
    environment:
      NGINX_ENVSUBST_OUTPUT_DIR: /etc/nginx/sites-enabled
    depends_on:
      - backend
    networks:
      - prod


  nginx:
    image: nginx:stable-alpine
    ports:
      - "80:80"
      - "443:443"
    depends_on:
      - backend
      - frontend
    volumes:
      - './nginx.conf:/etc/nginx/nginx.conf'
    networks:
      - prod
